import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { store } from '@/redux/store';
import { Provider } from 'react-redux';
import Providers from './Providers';
import { twMerge } from 'tailwind-merge';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Community Canvas',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, 'bg-primary text-primary')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
